(()=>{'use strict';
const KEY='dzienny.v1', categories=[['food','🍔','Jedzenie'],['fuel','⛽','Paliwo'],['home','🏠','Dom'],['fun','🎮','Rozrywka'],['shopping','🛍️','Zakupy'],['transport','🚗','Transport'],['other','📦','Inne']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], pad=n=>String(n).padStart(2,'0'), dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, parseDate=s=>new Date(`${s}T12:00:00`), monthKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}`, money=n=>new Intl.NumberFormat('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n), whole=n=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:0}).format(n), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=new Date();let selectedMonth=monthKey(today), selectedDay='', state=load(), toastTimer;
function blank(){return{budgets:{},expenses:[],theme:'system'}}function load(){try{return{...blank(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return blank()}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}function keyForMonth(m){return state.budgets[m]||{income:6000,bills:1500,fuel:500,savings:1000}}function expForMonth(m){return state.expenses.filter(x=>x.date.startsWith(m))}function icon(name){return (categories.find(c=>c[2]===name)||categories.at(-1))[1]}function daysInMonth(d){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}function monthName(m,cap=true){let d=parseDate(m+'-01');let t=new Intl.DateTimeFormat('pl-PL',{month:'long',year:'numeric'}).format(d);return cap?t.charAt(0).toLocaleUpperCase('pl-PL')+t.slice(1):t}
function update(){const data=keyForMonth(selectedMonth), expenses=expForMonth(selectedMonth), available=Math.max(0,data.income-data.bills-data.fuel-data.savings), spent=expenses.reduce((a,x)=>a+x.amount,0), rem=Math.max(0,available-spent), monthDate=parseDate(selectedMonth+'-01'), isCurrent=selectedMonth===monthKey(today), monthDays=daysInMonth(monthDate), daysLeft=isCurrent?Math.max(1,monthDays-today.getDate()+1):monthDays, dayStart=isCurrent?expenses.filter(x=>x.date<dateKey(today)).reduce((a,x)=>a+x.amount,0):0, safe=Math.max(0,(available-dayStart)/daysLeft), todays=expenses.filter(x=>isCurrent&&x.date===dateKey(today)), todaySpent=todays.reduce((a,x)=>a+x.amount,0), nextDays=isCurrent?Math.max(1,monthDays-today.getDate()):monthDays, actualSafe=Math.max(0,rem/nextDays);
$('#month-label').textContent=monthName(selectedMonth).split(' ')[0];$('#month-input').value=selectedMonth;$('#today-label').textContent=new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(today).replace(/^./,s=>s.toLocaleUpperCase('pl-PL'));$('#safe-today').textContent=money(Math.max(0,safe-todaySpent));$('#spent-total').textContent=`${whole(spent)} zł wydane`;$('#monthly-total').textContent=`${whole(available)} zł budżetu`;$('#remaining-total').textContent=`${money(rem)} zł`;
const liveToday=selectedMonth===monthKey(today);$('#spent-today').textContent=`${money(liveToday?todaySpent:0)} zł`;$('#month-progress').style.width=`${available?Math.min(100,spent/available*100):0}%`;let diff=safe-todaySpent,status=$('#status-message');status.classList.toggle('over',diff<0);status.textContent=diff>=0?`✓ Jesteś ${money(diff)} zł poniżej dzisiejszego limitu`:`↗ Limit przekroczony o ${money(-diff)} zł. Nowy plan to ${money(actualSafe)} zł dziennie.`;
const list=$('#today-expenses');list.innerHTML=todays.sort((a,b)=>b.created.localeCompare(a.created)).map(expenseRow).join('');$('#empty-today').classList.toggle('hidden',todays.length>0);list.classList.toggle('hidden',todays.length===0);renderCalendar();renderHistory();renderBudget(data,available);}
function expenseRow(x){let d=parseDate(x.date),when=x.date===dateKey(today)?new Intl.DateTimeFormat('pl-PL',{hour:'2-digit',minute:'2-digit'}).format(new Date(x.created)):new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'short'}).format(d);return `<div class="expense-row"><span class="expense-icon">${icon(x.category)}</span><div class="expense-info"><strong>${esc(x.category)}</strong><small>${x.note?esc(x.note)+' · ':''}${when}</small></div><strong class="expense-price">−${money(x.amount)} zł</strong><button class="delete-button" data-delete="${esc(x.id)}" aria-label="Usuń wydatek">×</button></div>`}
function renderCalendar(){const [y,m]=selectedMonth.split('-').map(Number),first=new Date(y,m-1,1),n=new Date(y,m,0).getDate(),offset=(first.getDay()+6)%7,monthExps=expForMonth(selectedMonth),available=keyForMonth(selectedMonth),dailyBase=Math.max(0,available.income-available.bills-available.fuel-available.savings)/n;$('#calendar-month').textContent=monthName(selectedMonth);let html=['Pn','Wt','Śr','Cz','Pt','So','Nd'].map(w=>`<div class="calendar-cell weekday">${w}</div>`).join('');for(let i=0;i<offset;i++)html+='<div class="calendar-cell"></div>';for(let day=1;day<=n;day++){let iso=`${selectedMonth}-${pad(day)}`,sum=monthExps.filter(x=>x.date===iso).reduce((a,x)=>a+x.amount,0),dot='';if(sum>0)dot=`<i class="dot ${sum>dailyBase*1.1?'red':sum>dailyBase*.85?'yellow':'green'}"></i>`;let label=new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(parseDate(iso));html+=`<div class="calendar-cell day-cell ${iso===dateKey(today)?'today':''} ${iso===selectedDay?'selected':''}" role="button" tabindex="0" aria-label="${label}" aria-pressed="${iso===selectedDay}" data-day="${iso}">${day}${dot}</div>`}$('#calendar-grid').innerHTML=html}
function renderHistory(){let all=expForMonth(selectedMonth),rows=all.filter(x=>!selectedDay||x.date===selectedDay).sort((a,b)=>b.date.localeCompare(a.date)||b.created.localeCompare(a.created));$('#history-heading').textContent=selectedDay?'Wydatki wybranego dnia':'Wydatki w tym miesiącu';$('#history-count').textContent=`${rows.length} ${rows.length===1?'wydatek':'wydatków'}`;let last='';$('#history-list').innerHTML=rows.length?rows.map(x=>{let head='';if(x.date!==last){last=x.date;head=`<div class="history-day">${new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(parseDate(x.date))}</div>`}return head+expenseRow(x)}).join(''):`<div class="empty-state"><span>🌿</span><p>${selectedDay?'Brak wydatków tego dnia.':'Historia zaczyna się od małych kroków.'}</p></div>`}
function renderBudget(data,available){$('#budget-available').textContent=`${money(available)} zł`;const f=$('#budget-form');for(const name of ['income','bills','fuel','savings'])f.elements[name].value=data[name]}
function showScreen(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===`screen-${name}`));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));window.scrollTo({top:0,behavior:'smooth'})}function showToast(t){let el=$('#toast');el.textContent=t;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2200)}
function openModal(){let f=$('#expense-form');f.reset();f.elements.date.value=dateKey(today);f.elements.category.value='Jedzenie';$('#expense-modal').classList.remove('hidden');setTimeout(()=>f.elements.amount.focus(),100)}function closeModal(){$('#expense-modal').classList.add('hidden')}
$('#category-select').innerHTML=categories.map(c=>`<option value="${c[2]}">${c[1]} ${c[2]}</option>`).join('');
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen)));$$('[data-action=add]').forEach(b=>b.addEventListener('click',openModal));$$('[data-action=close]').forEach(b=>b.addEventListener('click',closeModal));$('#expense-modal').addEventListener('click',e=>{if(e.target.id==='expense-modal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#expense-form').addEventListener('submit',e=>{e.preventDefault();let f=e.currentTarget,amount=Number(f.elements.amount.value);if(!(amount>0))return;state.expenses.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),amount,category:f.elements.category.value,date:f.elements.date.value,note:f.elements.note.value.trim(),created:new Date().toISOString()});save();closeModal();update();showToast('Wydatek dodany')});document.addEventListener('click',e=>{let b=e.target.closest('[data-delete]');if(b){state.expenses=state.expenses.filter(x=>x.id!==b.dataset.delete);save();update();showToast('Wydatek usunięty')}});
$('#budget-form').addEventListener('submit',e=>{e.preventDefault();let f=e.currentTarget;state.budgets[selectedMonth]=Object.fromEntries(['income','bills','fuel','savings'].map(n=>[n,Math.max(0,Number(f.elements[n].value)||0)]));save();update();showToast('Plan zapisany')});$('#month-input').addEventListener('change',e=>{if(e.target.value){selectedMonth=e.target.value;selectedDay='';update()}});$('#prev-month').addEventListener('click',()=>shiftMonth(-1));$('#next-month').addEventListener('click',()=>shiftMonth(1));function shiftMonth(i){let d=parseDate(selectedMonth+'-01');d.setMonth(d.getMonth()+i);selectedMonth=monthKey(d);selectedDay='';update()}
$('#calendar-grid').addEventListener('click',e=>{let cell=e.target.closest('[data-day]');if(cell){selectedDay=cell.dataset.day;renderCalendar();renderHistory()}});$('#calendar-grid').addEventListener('keydown',e=>{let cell=e.target.closest('[data-day]');if(cell&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectedDay=cell.dataset.day;renderCalendar();renderHistory()}});
function applyTheme(){let pref=state.theme||'system',dark=pref==='dark'||(pref==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.dataset.theme=dark?'dark':'light';$('#theme-select').value=pref;document.querySelector('meta[name=theme-color]').content=dark?'#161a17':'#f6f5f1'}$('#theme-select').addEventListener('change',e=>{state.theme=e.target.value;save();applyTheme()});matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',applyTheme);$('#export-data').addEventListener('click',()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Spendo-kopia-${dateKey(today)}.json`;a.click();URL.revokeObjectURL(a.href);showToast('Kopia danych pobrana')});
applyTheme();update();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('/sw.js').catch(()=>{});
})();
