const fs=require('node:fs'),zlib=require('node:zlib'),assert=require('node:assert/strict');
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));
const html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');
const sizes={'pulnora-icon-192.png':192,'pulnora-icon-512.png':512,'pulnora-icon-maskable-512.png':512,'pulnora-apple-touch-icon-180.png':180,'pulnora-favicon-32.png':32,'pulnora-favicon-48.png':48,'pulnora-icon-1024.png':1024};
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function png(file,size){const b=fs.readFileSync(file);assert.equal(b.subarray(0,8).toString('hex'),'89504e470d0a1a0a');let at=8,compressed=[],ended=false;while(at<b.length){const n=b.readUInt32BE(at),type=b.toString('ascii',at+4,at+8),data=b.subarray(at+8,at+8+n);assert.equal(crc(b.subarray(at+4,at+8+n)),b.readUInt32BE(at+8+n),file+': CRC');if(type==='IHDR'){assert.equal(data.readUInt32BE(0),size);assert.equal(data.readUInt32BE(4),size);assert.equal(data[8],8);assert.equal(data[9],2);assert.equal(data[12],0);}if(type==='IDAT')compressed.push(data);if(type==='IEND')ended=true;at+=12+n;}assert.ok(ended);const raw=zlib.inflateSync(Buffer.concat(compressed)),stride=size*3;assert.equal(raw.length,(stride+1)*size);const pixels=Buffer.alloc(stride*size);for(let y=0;y<size;y++){const filter=raw[y*(stride+1)];assert.ok(filter<=4);for(let x=0;x<stride;x++){const a=x>=3?pixels[y*stride+x-3]:0,up=y?pixels[(y-1)*stride+x]:0,c=y&&x>=3?pixels[(y-1)*stride+x-3]:0;let predictor=0;if(filter===1)predictor=a;if(filter===2)predictor=up;if(filter===3)predictor=Math.floor((a+up)/2);if(filter===4){const p=a+up-c,pa=Math.abs(p-a),pb=Math.abs(p-up),pc=Math.abs(p-c);predictor=pa<=pb&&pa<=pc?a:pb<=pc?up:c;}pixels[y*stride+x]=(raw[y*(stride+1)+1+x]+predictor)&255;}}return pixels;}
for(const [name,size] of Object.entries(sizes)){const pixels=png('brand-assets/'+name,size);if(name.includes('maskable')){let gold=0,maxRadius=0;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=(y*size+x)*3;if(pixels[i]>90&&pixels[i]>pixels[i+2]+30&&pixels[i+1]>pixels[i+2]+10){gold++;maxRadius=Math.max(maxRadius,Math.hypot(x+.5-size/2,y+.5-size/2));}}assert.ok(gold>1000);assert.ok(maxRadius<=size*.4,`Gold mark outside safe circle: ${maxRadius}`);console.log('OK opaque maskable, gold mark radius:',maxRadius.toFixed(2),'<=',size*.4);}console.log('OK PNG',name,size);}
assert.equal(manifest.id,'/');assert.equal(manifest.start_url,'/');assert.equal(manifest.scope,undefined);assert.equal(manifest.short_name,'Pulnora');
assert.deepEqual(manifest.icons.map(i=>i.purpose),['any','any','maskable']);
for(const icon of manifest.icons){assert.ok(fs.existsSync('.'+icon.src));assert.ok(sw.includes("'"+icon.src+"'"));assert.equal(icon.type,'image/png');}
for(const name of ['pulnora-apple-touch-icon-180.png','pulnora-favicon-32.png','pulnora-favicon-48.png','pulnora-icon.svg']){assert.ok(html.includes('/brand-assets/'+name));assert.ok(sw.includes('/brand-assets/'+name));}
assert.ok(html.includes('alt="Logo Pulnora"'));assert.ok(!html.includes('class="brand-mark">d.'));
for(const old of ['/apple-touch-icon.png','/icon-192.png','/icon-512.png']){assert.ok(!html.includes(old));assert.ok(!sw.includes("'"+old+"'"));assert.ok(!manifest.icons.some(i=>i.src===old));}
const svg=fs.readFileSync('brand-assets/pulnora-icon.svg','utf8');assert.ok(svg.includes('viewBox="0 0 1024 1024"'));assert.ok(!/<script|onload=|<image|<foreignObject|href=/i.test(svg));
console.log('OK icon wiring, PWA identity, offline cache, SVG and legacy references');
